version: '3'

services:
  web:
    build: .
    container_name: django_stripe
    ports:
      - "8000:8000"
    volumes:
      - ./payment_project:/app  # Правильный путь к manage.py
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
